# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"im2id": "index.ipynb"}

modules = ["core.py"]

doc_url = "https://sizhky.github.io/src/"

git_url = "https://github.com/sizhky/src/tree/master/"

def custom_doc_links(name): return None
