# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/index.ipynb (unless otherwise specified).

__all__ = ['im2id']

# Cell

from torch_snippets import *
from pytesseract import image_to_string
def im2id(im):
    x = image_to_string(im).replace('\n', ' ')
    x = ' '.join(x.split())
    y = re.findall('[\d\s]{11,16}', x)
    y = set([_y.strip() for _y in y])
    y = [_y for _y in y if len(_y.replace(' ', '')) == 12]
    return y